services:
  backend:
    build: ./server
    restart: always
    ports:
      - 9999:${SERVER_PORT}
#  client:
#    build: ./client
#    restart: always
#    ports:
#      - 8080:${CLIENT_PORT}
#      - 8888:${CLIENT_PORT}
